#!/usr/bin/env node
/**
 * Principle exception ledger.
 *
 * Design principles in this repo may be broken — but only out loud. Every
 * violation carries a `PRINCIPLE-EXCEPTION` block arguing the case. This script
 * collects them all, checks that each one is properly argued, and writes a
 * report.
 *
 * The point is visibility. An exception nobody ever looks at again is just a
 * violation that learned the paperwork, so the ledger makes the full set
 * reviewable in one place, and CI fails on a malformed block.
 *
 *   node .claude/scripts/principles-ledger.mjs [--write] [--quiet]
 *
 *   --write   also render the report to docs/internal/principle-exceptions.md
 *   --quiet   only print on failure
 *
 * Exit code: 0 when every block is well-formed, 1 otherwise.
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SCAN_ROOTS = ['packages', 'apps'];
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.js', '.mjs']);
const IGNORED_DIRECTORIES = new Set([
  'node_modules',
  'dist',
  'coverage',
  '.angular',
  '.git',
  'out-tsc',
]);

const MARKER = 'PRINCIPLE-EXCEPTION:';
const REQUIRED_FIELDS = ['Why', 'Alternative considered', 'Revisit'];

/**
 * Principles the ledger recognises. An unknown name is reported as a warning
 * rather than an error: the list can legitimately lag behind
 * `.claude/rules/design-principles.md`, and a typo is worth flagging without
 * breaking the build over it.
 */
const KNOWN_PRINCIPLES = new Set([
  'SRP',
  'OCP',
  'LSP',
  'ISP',
  'DIP',
  'DRY',
  'KISS',
  'YAGNI',
  'TELL-DONT-ASK',
  'DEMETER',
  'POLA',
  'EDP',
  'KOP',
  'SOC',
  'LOW-COUPLING',
  'HIGH-COHESION',
]);

async function* walkSourceFiles(directory) {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return; // A scan root that does not exist yet is not an error.
  }

  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      if (!IGNORED_DIRECTORIES.has(entry.name)) yield* walkSourceFiles(path);
    } else if (SOURCE_EXTENSIONS.has(extname(entry.name))) {
      yield path;
    }
  }
}

/** Strips the leading `//` and one space of indentation from a comment line. */
function commentBody(line) {
  const match = line.match(/^\s*\/\/ ?(.*)$/);
  return match ? match[1] : null;
}

/**
 * Reads the contiguous run of `//` lines starting at `startIndex` and splits it
 * into `Field: value` entries, joining wrapped continuation lines.
 */
function parseBlock(lines, startIndex) {
  const fields = new Map();
  let currentField = null;

  for (let i = startIndex + 1; i < lines.length; i++) {
    const body = commentBody(lines[i]);
    if (body === null) break; // Block ends at the first non-comment line.

    const fieldMatch = body.match(/^([A-Za-z][A-Za-z ]*?):\s*(.*)$/);
    if (fieldMatch) {
      currentField = fieldMatch[1].trim();
      fields.set(currentField, fieldMatch[2].trim());
    } else if (currentField && body.trim()) {
      fields.set(currentField, `${fields.get(currentField)} ${body.trim()}`.trim());
    }
  }

  return fields;
}

async function collectExceptions() {
  const found = [];

  for (const root of SCAN_ROOTS) {
    for await (const file of walkSourceFiles(join(REPO_ROOT, root))) {
      const lines = (await readFile(file, 'utf8')).split('\n');

      for (const [index, line] of lines.entries()) {
        const markerPosition = line.indexOf(MARKER);
        if (markerPosition === -1 || commentBody(line) === null) continue;

        const principle = line.slice(markerPosition + MARKER.length).trim();
        const fields = parseBlock(lines, index);

        found.push({
          file: relative(REPO_ROOT, file),
          line: index + 1,
          principle,
          fields,
          missing: REQUIRED_FIELDS.filter((f) => !fields.get(f)),
          unknownPrinciple: principle !== '' && !KNOWN_PRINCIPLES.has(principle.toUpperCase()),
        });
      }
    }
  }

  return found.sort((a, b) => a.file.localeCompare(b.file) || a.line - b.line);
}

function renderMarkdown(exceptions) {
  const header = [
    '# Principle exceptions',
    '',
    '> Generated by `pnpm principles:ledger`. Do not edit by hand.',
    '',
    'Every place this codebase knowingly breaks one of its own design',
    'principles, with the argument for doing so. See',
    '`.claude/rules/design-principles.md` for the principles themselves.',
    '',
  ];

  if (exceptions.length === 0) {
    return [...header, 'No exceptions recorded. Every rule currently holds.', ''].join('\n');
  }

  const byPrinciple = new Map();
  for (const exception of exceptions) {
    const key = exception.principle || '(unspecified)';
    byPrinciple.set(key, [...(byPrinciple.get(key) ?? []), exception]);
  }

  const sections = [
    `${exceptions.length} exception(s) across ${byPrinciple.size} principle(s).`,
    '',
  ];

  for (const [principle, group] of [...byPrinciple].sort()) {
    sections.push(`## ${principle}`, '');
    for (const { file, line, fields } of group) {
      sections.push(`### \`${file}\`:${line}`, '');
      for (const field of REQUIRED_FIELDS) {
        sections.push(`- **${field}:** ${fields.get(field) ?? '_missing_'}`);
      }
      sections.push('');
    }
  }

  return [...header, ...sections].join('\n');
}

function report(exceptions, { quiet }) {
  const malformed = exceptions.filter((e) => e.missing.length > 0 || e.principle === '');
  const unknown = exceptions.filter((e) => e.unknownPrinciple);

  if (!quiet || malformed.length > 0) {
    console.log(`\nPrinciple exception ledger — ${exceptions.length} recorded\n`);

    for (const { file, line, principle, missing } of exceptions) {
      const status = missing.length > 0 ? 'INVALID' : 'ok';
      console.log(`  [${status}] ${principle || '(unspecified)'} — ${file}:${line}`);
      if (missing.length > 0) {
        console.log(`           missing field(s): ${missing.join(', ')}`);
      }
    }
  }

  for (const { file, line, principle } of unknown) {
    console.warn(`\n  warning: unrecognised principle "${principle}" at ${file}:${line}`);
    console.warn('           check the spelling against .claude/rules/design-principles.md');
  }

  if (malformed.length > 0) {
    console.error(
      `\n✗ ${malformed.length} malformed block(s). Each exception needs ` +
        `"${MARKER} <PRINCIPLE>" followed by ${REQUIRED_FIELDS.join(', ')}.\n`,
    );
    return 1;
  }

  if (!quiet) console.log('\n✓ All exception blocks are well-formed.\n');
  return 0;
}

const options = {
  write: process.argv.includes('--write'),
  quiet: process.argv.includes('--quiet'),
};

const exceptions = await collectExceptions();

if (options.write) {
  const target = join(REPO_ROOT, 'docs', 'internal', 'principle-exceptions.md');
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, renderMarkdown(exceptions), 'utf8');
  if (!options.quiet) console.log(`Report written to ${relative(REPO_ROOT, target)}`);
}

process.exit(report(exceptions, options));
